<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<package format="1" xmlns="https://wiki.freecad.org/Package_Metadata">
  <name>freecadGSD</name>
  <description>CATIA GSD-like curves and surface helpers for FreeCAD, based on Curves Workbench.</description>
  <version>0.6.81</version>
  <date>2026-08-24</date>
  <author>Christophe Grellier</author>
  <maintainer email="">Balazs / Ovadclaw</maintainer>
  <license file="LICENSE-CODE">LGPL-2.1-or-later</license>
  <license file="LICENSE-TIGL">Apache-2.0</license>
  <url type="repository" branch="main">https://github.com/airforce-io/freecadGSD</url>
  <url type="documentation">https://github.com/airforce-io/freecadGSD</url>

  <content>
    <workbench>
      <name>freecadGSD</name>
      <classname>CurvesWorkbench</classname>
      <description>CATIA GSD-like curves and surface helpers for FreeCAD, based on Curves Workbench.</description>
      <version>0.6.81</version>
      <subdirectory>./</subdirectory>
      <icon>freecad/Curves/resources/icons/blendSurf.svg</icon>
      <freecadmin>0.21.2</freecadmin>
      <depend>numpy</depend>
      <depend>scipy</depend>
      <tag>curves</tag>
      <tag>nurbs</tag>
      <tag>gsd</tag>
      <tag>surface</tag>
      <tag>gensurf</tag>
    </workbench>
  </content>

</package>
